/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAgentRouteImport } from './routes/_authenticated/agent'
import { Route as AuthenticatedCandidaturesRouteImport } from './routes/_authenticated/candidatures'
import { Route as AuthenticatedCoachRouteImport } from './routes/_authenticated/coach'
import { Route as AuthenticatedCvRouteImport } from './routes/_authenticated/cv'
import { Route as AuthenticatedEntreprisesRouteImport } from './routes/_authenticated/entreprises'
import { Route as AuthenticatedEntretienRouteImport } from './routes/_authenticated/entretien'
import { Route as AuthenticatedOffresRouteImport } from './routes/_authenticated/offres'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedTableauDeBordRouteImport } from './routes/_authenticated/tableau-de-bord'
import { Route as AuthenticatedRecruteurOffresRouteImport } from './routes/_authenticated/recruteur/offres'
import { Route as AuthenticatedRecruteurPipelineRouteImport } from './routes/_authenticated/recruteur/pipeline'
import { Route as ApiVoiceSpeakRouteImport } from './routes/api/voice/speak'
import { Route as ApiVoiceTranscribeRouteImport } from './routes/api/voice/transcribe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAgentRoute = AuthenticatedAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCandidaturesRoute =
  AuthenticatedCandidaturesRouteImport.update({
    id: '/candidatures',
    path: '/candidatures',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoachRoute = AuthenticatedCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCvRoute = AuthenticatedCvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEntreprisesRoute =
  AuthenticatedEntreprisesRouteImport.update({
    id: '/entreprises',
    path: '/entreprises',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntretienRoute = AuthenticatedEntretienRouteImport.update({
  id: '/entretien',
  path: '/entretien',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOffresRoute = AuthenticatedOffresRouteImport.update({
  id: '/offres',
  path: '/offres',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTableauDeBordRoute =
  AuthenticatedTableauDeBordRouteImport.update({
    id: '/tableau-de-bord',
    path: '/tableau-de-bord',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecruteurOffresRoute =
  AuthenticatedRecruteurOffresRouteImport.update({
    id: '/recruteur/offres',
    path: '/recruteur/offres',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecruteurPipelineRoute =
  AuthenticatedRecruteurPipelineRouteImport.update({
    id: '/recruteur/pipeline',
    path: '/recruteur/pipeline',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiVoiceSpeakRoute = ApiVoiceSpeakRouteImport.update({
  id: '/api/voice/speak',
  path: '/api/voice/speak',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceTranscribeRoute = ApiVoiceTranscribeRouteImport.update({
  id: '/api/voice/transcribe',
  path: '/api/voice/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agent': typeof AuthenticatedAgentRoute
  '/candidatures': typeof AuthenticatedCandidaturesRoute
  '/coach': typeof AuthenticatedCoachRoute
  '/cv': typeof AuthenticatedCvRoute
  '/entreprises': typeof AuthenticatedEntreprisesRoute
  '/entretien': typeof AuthenticatedEntretienRoute
  '/offres': typeof AuthenticatedOffresRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/recruteur/offres': typeof AuthenticatedRecruteurOffresRoute
  '/recruteur/pipeline': typeof AuthenticatedRecruteurPipelineRoute
  '/api/voice/speak': typeof ApiVoiceSpeakRoute
  '/api/voice/transcribe': typeof ApiVoiceTranscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agent': typeof AuthenticatedAgentRoute
  '/candidatures': typeof AuthenticatedCandidaturesRoute
  '/coach': typeof AuthenticatedCoachRoute
  '/cv': typeof AuthenticatedCvRoute
  '/entreprises': typeof AuthenticatedEntreprisesRoute
  '/entretien': typeof AuthenticatedEntretienRoute
  '/offres': typeof AuthenticatedOffresRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/recruteur/offres': typeof AuthenticatedRecruteurOffresRoute
  '/recruteur/pipeline': typeof AuthenticatedRecruteurPipelineRoute
  '/api/voice/speak': typeof ApiVoiceSpeakRoute
  '/api/voice/transcribe': typeof ApiVoiceTranscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/agent': typeof AuthenticatedAgentRoute
  '/_authenticated/candidatures': typeof AuthenticatedCandidaturesRoute
  '/_authenticated/coach': typeof AuthenticatedCoachRoute
  '/_authenticated/cv': typeof AuthenticatedCvRoute
  '/_authenticated/entreprises': typeof AuthenticatedEntreprisesRoute
  '/_authenticated/entretien': typeof AuthenticatedEntretienRoute
  '/_authenticated/offres': typeof AuthenticatedOffresRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/_authenticated/recruteur/offres': typeof AuthenticatedRecruteurOffresRoute
  '/_authenticated/recruteur/pipeline': typeof AuthenticatedRecruteurPipelineRoute
  '/api/voice/speak': typeof ApiVoiceSpeakRoute
  '/api/voice/transcribe': typeof ApiVoiceTranscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agent'
    | '/candidatures'
    | '/coach'
    | '/cv'
    | '/entreprises'
    | '/entretien'
    | '/offres'
    | '/profil'
    | '/tableau-de-bord'
    | '/recruteur/offres'
    | '/recruteur/pipeline'
    | '/api/voice/speak'
    | '/api/voice/transcribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/agent'
    | '/candidatures'
    | '/coach'
    | '/cv'
    | '/entreprises'
    | '/entretien'
    | '/offres'
    | '/profil'
    | '/tableau-de-bord'
    | '/recruteur/offres'
    | '/recruteur/pipeline'
    | '/api/voice/speak'
    | '/api/voice/transcribe'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/agent'
    | '/_authenticated/candidatures'
    | '/_authenticated/coach'
    | '/_authenticated/cv'
    | '/_authenticated/entreprises'
    | '/_authenticated/entretien'
    | '/_authenticated/offres'
    | '/_authenticated/profil'
    | '/_authenticated/tableau-de-bord'
    | '/_authenticated/recruteur/offres'
    | '/_authenticated/recruteur/pipeline'
    | '/api/voice/speak'
    | '/api/voice/transcribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiVoiceSpeakRoute: typeof ApiVoiceSpeakRoute
  ApiVoiceTranscribeRoute: typeof ApiVoiceTranscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/agent': {
      id: '/_authenticated/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AuthenticatedAgentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candidatures': {
      id: '/_authenticated/candidatures'
      path: '/candidatures'
      fullPath: '/candidatures'
      preLoaderRoute: typeof AuthenticatedCandidaturesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coach': {
      id: '/_authenticated/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AuthenticatedCoachRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cv': {
      id: '/_authenticated/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof AuthenticatedCvRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entreprises': {
      id: '/_authenticated/entreprises'
      path: '/entreprises'
      fullPath: '/entreprises'
      preLoaderRoute: typeof AuthenticatedEntreprisesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entretien': {
      id: '/_authenticated/entretien'
      path: '/entretien'
      fullPath: '/entretien'
      preLoaderRoute: typeof AuthenticatedEntretienRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/offres': {
      id: '/_authenticated/offres'
      path: '/offres'
      fullPath: '/offres'
      preLoaderRoute: typeof AuthenticatedOffresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tableau-de-bord': {
      id: '/_authenticated/tableau-de-bord'
      path: '/tableau-de-bord'
      fullPath: '/tableau-de-bord'
      preLoaderRoute: typeof AuthenticatedTableauDeBordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recruteur/offres': {
      id: '/_authenticated/recruteur/offres'
      path: '/recruteur/offres'
      fullPath: '/recruteur/offres'
      preLoaderRoute: typeof AuthenticatedRecruteurOffresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recruteur/pipeline': {
      id: '/_authenticated/recruteur/pipeline'
      path: '/recruteur/pipeline'
      fullPath: '/recruteur/pipeline'
      preLoaderRoute: typeof AuthenticatedRecruteurPipelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/voice/speak': {
      id: '/api/voice/speak'
      path: '/api/voice/speak'
      fullPath: '/api/voice/speak'
      preLoaderRoute: typeof ApiVoiceSpeakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice/transcribe': {
      id: '/api/voice/transcribe'
      path: '/api/voice/transcribe'
      fullPath: '/api/voice/transcribe'
      preLoaderRoute: typeof ApiVoiceTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgentRoute: typeof AuthenticatedAgentRoute
  AuthenticatedCandidaturesRoute: typeof AuthenticatedCandidaturesRoute
  AuthenticatedCoachRoute: typeof AuthenticatedCoachRoute
  AuthenticatedCvRoute: typeof AuthenticatedCvRoute
  AuthenticatedEntreprisesRoute: typeof AuthenticatedEntreprisesRoute
  AuthenticatedEntretienRoute: typeof AuthenticatedEntretienRoute
  AuthenticatedOffresRoute: typeof AuthenticatedOffresRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedTableauDeBordRoute: typeof AuthenticatedTableauDeBordRoute
  AuthenticatedRecruteurOffresRoute: typeof AuthenticatedRecruteurOffresRoute
  AuthenticatedRecruteurPipelineRoute: typeof AuthenticatedRecruteurPipelineRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgentRoute: AuthenticatedAgentRoute,
  AuthenticatedCandidaturesRoute: AuthenticatedCandidaturesRoute,
  AuthenticatedCoachRoute: AuthenticatedCoachRoute,
  AuthenticatedCvRoute: AuthenticatedCvRoute,
  AuthenticatedEntreprisesRoute: AuthenticatedEntreprisesRoute,
  AuthenticatedEntretienRoute: AuthenticatedEntretienRoute,
  AuthenticatedOffresRoute: AuthenticatedOffresRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedTableauDeBordRoute: AuthenticatedTableauDeBordRoute,
  AuthenticatedRecruteurOffresRoute: AuthenticatedRecruteurOffresRoute,
  AuthenticatedRecruteurPipelineRoute: AuthenticatedRecruteurPipelineRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiVoiceSpeakRoute: ApiVoiceSpeakRoute,
  ApiVoiceTranscribeRoute: ApiVoiceTranscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
